<<<<<<< HEAD
---
title: "Lab1_Evolutionary Genomics Course"
author: "Melise Edwards"
date: "9/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Exercise 1

For x = 3 and y = 15, compute the sum, difference, product and quotient of x and y


```{r}
x <- 3
y <- 15

x + y
x - y
x * y
y / x

```

### Exercise 2

For x = 2 and y = 3, Test x^5 is greater than y^4 and return a logical value

```{r}
x <- 2
y <- 3

isFALSE(x^5 > y^4)
```

### Exercise 3

Create a vector of the values 22, 62, 148, 43 and 129. Determine the sum of the vector. Divide each value in the vector by the sum to determine relate frequency.

```{r}
Vector <- c(22, 62, 148, 43, 129)

sum(Vector)

Vector[1:4]/sum(Vector)



```

### Exercise 4

Create a vector of the nucleotides A, T, C and G. Sort the vector.

```{r}

DNA <- c("A", "T", "C", "G")

sort(DNA, decreasing=T)

```

=======
---
title: "Lab1_Evolutionary Genomics Course"
author: "Melise Edwards"
date: "9/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Exercise 1

For x = 3 and y = 15, compute the sum, difference, product and quotient of x and y


```{r}
x <- 3
y <- 15

x + y
x - y
x * y
y / x

```

### Exercise 2

For x = 2 and y = 3, Test x^5 is greater than y^4 and return a logical value

```{r}
x <- 2
y <- 3

isFALSE(x^5 > y^4)
```

### Exercise 3

Create a vector of the values 22, 62, 148, 43 and 129. Determine the sum of the vector. Divide each value in the vector by the sum to determine relate frequency.

```{r}
Vector <- c(22, 62, 148, 43, 129)

sum(Vector)

Vector[1:4]/sum(Vector)



```

### Exercise 4

Create a vector of the nucleotides A, T, C and G. Sort the vector.

```{r}

DNA <- c("A", "T", "C", "G")

sort(DNA, decreasing=T)

```

>>>>>>> 6f6b4563718bcf44aa7f6dc404bf03fcc12ada87
